export const AUTH_SERVICE = 'AUTH_SERVICE';
export const SMS_SERVICE = 'SMS_SERVICE';
export const EMAIL_SERVICE = 'EMAIL_SERVICE';
export const TOKEN_SERVICE = 'TOKEN_SERVICE';
export const USERS_SERVICE = 'USERS_SERVICE';
export const VERIFICATIONS_SERVICE = 'VERIFICATIONS_SERVICE';
export const USER_METADATA_SERVICE = 'USER_METADATA_SERVICE';

export const PUB_SUB = 'PUB_SUB';
